package Online;

import java.awt.Button;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.Date;
import java.text.DateFormat;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Asus
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Button button = new Button();

        pn.add(button);

        pn.revalidate();    // as @Hovercraft Full Of Eels suggested
        pn.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Signup = new javax.swing.JFrame();
        signup_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        signup_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        signup_passwd = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        signup_passwd2 = new javax.swing.JPasswordField();
        signup_show = new javax.swing.JRadioButton();
        create_acc = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        home = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        tutorials = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        tut = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextPane();
        cb = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        buttonGroup3 = new javax.swing.ButtonGroup();
        Clienthost = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        stime = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ftime = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        livec = new javax.swing.JButton();
        host = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        lvc = new javax.swing.JFrame();
        jp1 = new javax.swing.JPanel();
        problempage = new javax.swing.JFrame();
        qchoose = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextPane();
        compile = new javax.swing.JButton();
        run = new javax.swing.JButton();
        lchoose = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        passwd = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        pn = new javax.swing.JPanel();

        Signup.setMinimumSize(new java.awt.Dimension(684, 511));

        signup_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_nameActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Email");

        signup_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_emailActionPerformed(evt);
            }
        });

        jLabel5.setText("Password");

        signup_passwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_passwdActionPerformed(evt);
            }
        });

        jLabel6.setText("Re Enter Password");

        signup_passwd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_passwd2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(signup_show);
        signup_show.setText("Show Password");
        signup_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_showActionPerformed(evt);
            }
        });

        create_acc.setText("Create Account");
        create_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_accActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SIGNUP");

        javax.swing.GroupLayout SignupLayout = new javax.swing.GroupLayout(Signup.getContentPane());
        Signup.getContentPane().setLayout(SignupLayout);
        SignupLayout.setHorizontalGroup(
            SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SignupLayout.createSequentialGroup()
                        .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SignupLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signup_name, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SignupLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signup_email, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addComponent(signup_show)
                        .addGap(37, 37, 37))
                    .addGroup(SignupLayout.createSequentialGroup()
                        .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signup_passwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signup_passwd2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(185, 185, 185))))
            .addGroup(SignupLayout.createSequentialGroup()
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignupLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SignupLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(create_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SignupLayout.setVerticalGroup(
            SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupLayout.createSequentialGroup()
                        .addComponent(signup_name, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGap(20, 20, 20)
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignupLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signup_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(signup_show)
                        .addGap(28, 28, 28)))
                .addGroup(SignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signup_passwd2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(create_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        home.setMinimumSize(new java.awt.Dimension(470, 470));
        home.setResizable(false);

        jLabel9.setText("Programming Tutorials and Practise Problems");

        tutorials.setText("Tutorials");
        tutorials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialsActionPerformed(evt);
            }
        });

        jButton3.setText("Contests");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Algorithms n Coding !!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home.getContentPane());
        home.getContentPane().setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(tutorials, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(logout)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(tutorials, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(logout)
                .addGap(36, 36, 36))
        );

        tut.setMinimumSize(new java.awt.Dimension(600, 500));

        txt1.setEditable(false);
        jScrollPane2.setViewportView(txt1);

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Number Theory", "Dynamic Programming", "Graphs" }));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });

        jLabel10.setText("Tutorials");

        javax.swing.GroupLayout tutLayout = new javax.swing.GroupLayout(tut.getContentPane());
        tut.getContentPane().setLayout(tutLayout);
        tutLayout.setHorizontalGroup(
            tutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tutLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        tutLayout.setVerticalGroup(
            tutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tutLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jTextPane1);

        Clienthost.setMinimumSize(new java.awt.Dimension(1000, 1000));

        jLabel11.setText("Contest Name");

        name.setText("ssss");

        jLabel12.setText("Contest Date");

        jLabel13.setText("Contest Starts At:");

        stime.setText("sss");

        jLabel14.setText("Contest Ends At:");

        ftime.setText("ssss");

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Contst Type:", "School", "Company", "College", "Others" }));

        livec.setText("Check The Valid contest dates And Time");
        livec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livecActionPerformed(evt);
            }
        });

        host.setText("Manage Contest");
        host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClienthostLayout = new javax.swing.GroupLayout(Clienthost.getContentPane());
        Clienthost.getContentPane().setLayout(ClienthostLayout);
        ClienthostLayout.setHorizontalGroup(
            ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienthostLayout.createSequentialGroup()
                .addGroup(ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClienthostLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stime, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(host, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ClienthostLayout.createSequentialGroup()
                        .addGroup(ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ClienthostLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(livec, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ClienthostLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ClienthostLayout.createSequentialGroup()
                                        .addGroup(ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ClienthostLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(90, 90, 90)
                                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(77, 77, 77)
                                        .addGroup(ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(ftime, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );
        ClienthostLayout.setVerticalGroup(
            ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienthostLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClienthostLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftime, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(stime)))
                    .addGroup(ClienthostLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(ClienthostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(host, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(livec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        lvc.setMinimumSize(new java.awt.Dimension(1000, 1000));

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lvcLayout = new javax.swing.GroupLayout(lvc.getContentPane());
        lvc.getContentPane().setLayout(lvcLayout);
        lvcLayout.setHorizontalGroup(
            lvcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lvcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        lvcLayout.setVerticalGroup(
            lvcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lvcLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        problempage.setMinimumSize(new java.awt.Dimension(800, 800));

        qchoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "problem1", "problem2", "problem3", "problem4", "problem5", "problem6", "problem7" }));
        qchoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qchooseActionPerformed(evt);
            }
        });

        question.setColumns(20);
        question.setRows(5);
        question.setText("print the sum of a and b . ");
        jScrollPane4.setViewportView(question);

        jScrollPane5.setViewportView(editor);

        compile.setText("compile");
        compile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileActionPerformed(evt);
            }
        });

        run.setText("run");
        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });

        lchoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "c", "c++", "java", "python" }));

        javax.swing.GroupLayout problempageLayout = new javax.swing.GroupLayout(problempage.getContentPane());
        problempage.getContentPane().setLayout(problempageLayout);
        problempageLayout.setHorizontalGroup(
            problempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(problempageLayout.createSequentialGroup()
                .addGroup(problempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(problempageLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(problempageLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(problempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(problempageLayout.createSequentialGroup()
                                .addComponent(qchoose, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                                .addComponent(lchoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(problempageLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(compile)
                        .addGap(61, 61, 61)
                        .addComponent(run)))
                .addGap(63, 63, 63))
        );
        problempageLayout.setVerticalGroup(
            problempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(problempageLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(problempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qchoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lchoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(problempageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compile)
                    .addComponent(run))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        user.setText("cms");

        passwd.setText("cms");

        login.setText("Login");
        login.setEnabled(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        signup.setText("SIGNUP");
        signup.setEnabled(false);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        jLabel8.setText("Who You Are??");

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("User");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Host");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(user)
                    .addComponent(passwd, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(19, 19, 19)
                        .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        Signup.setVisible(true);
    }//GEN-LAST:event_signupActionPerformed

    private void signup_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_nameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_signup_nameActionPerformed

    private void create_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_accActionPerformed
        // TODO add your handling code here:
        String name = signup_name.getText();
        String email = signup_email.getText();
        String passwd = signup_passwd.getText();
        String p2 = signup_passwd2.getText();
        if (name.equals("") || email.equals("") || passwd.equals("") || p2.equals("")) {
            JOptionPane.showMessageDialog(null, "enter all fields");
        } else if (!passwd.equals(p2)) {
            JOptionPane.showMessageDialog(null, "password didnt match");
        } else {
            String query;
            if (flag == 1) {
                query = "Insert Into users VALUES ('" + name + "','" + passwd + "','" + email + "')";
            } else {
                query = "Insert Into host VALUES ('" + name + "','" + passwd + "','" + email + "')";
            }
            database db = new database();
            db.opendb(query, 0);
            JOptionPane.showMessageDialog(null, "Signup Successfull");
        }
    }//GEN-LAST:event_create_accActionPerformed

    private void signup_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_emailActionPerformed

    private void signup_passwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_passwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_passwdActionPerformed

    private void signup_passwd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_passwd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_passwd2ActionPerformed

    private void signup_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_showActionPerformed
        signup_passwd.show();
    }//GEN-LAST:event_signup_showActionPerformed
    int flag = 0;
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        login.setText("User Login");
        signup.setText("User Signup");
        flag = 1;
        login.setEnabled(true);
        signup.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        login.setText("Host Login");
        signup.setText("Host Signup");
        flag = 2;
        signup.setEnabled(true);
        login.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    static Socket s;
    static DataInputStream din;

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        Request r = null;// to create an object 
        try {
            System.out.println("Starting Server...");
            r = new Request(); //object created
            int status = r.start();
            if (status == 1) {
                r.cont();
            }
            //System.out.println((r.flag+""));
            if (status == 1 && r.flag == 1) {
                String luser = user.getText();
                String lpasswd = passwd.getText();
                if (luser.equals("") || lpasswd.equals("")) {
                    JOptionPane.showMessageDialog(null, "enter all fields");
                } else {
                    String query;
                    if (flag == 1) {
                        query = "Select * from users where username='" + luser + "' and password='" + lpasswd + "'";
                    } else {
                        query = "Select * from host where username='" + luser + "' and password='" + lpasswd + "'";
                    }
                    database d = new database();
                    d.opendb(query, 1);
                    if (d.cnt == 1) {
                        if (flag == 1) {
                            home.setVisible(true);

                        } else {
                            Clienthost.setVisible(true);
                        }
                        dispose();
                    }

                }
            } else {
                JOptionPane.showMessageDialog(null, "First Turn ON server !!");
            }
        } catch (Exception e) {
            System.out.println("error");
        }

    }//GEN-LAST:event_loginActionPerformed

    private void tutorialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialsActionPerformed
        // TODO add your handling code here:
        tut.setVisible(true);
    }//GEN-LAST:event_tutorialsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        problempage.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:
        String str = cb.getSelectedItem().toString();
        if (str.equals("Number Theory")) {
            txt1.setText("abc");
        } else if (str.equals("Dynamic Programming")) {
            txt1.setText("dp");
        } else if (str.equals("Graphs")) {
            txt1.setText("gr");
        }
    }//GEN-LAST:event_cbActionPerformed
     public final JLabel jlb[][] = new JLabel[100][3];
      public  void getval(int i,int j)
      {
          jp1.add(jlb[i][j] = new JLabel());
      }
      
    private void livecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livecActionPerformed
        // TODO add your handling code here:
        
        

        lvc.setVisible(true);
        LiveContest lv = new LiveContest();
        lv.func();
        database db = new database();
        int size = db.query("select * from contest");
        System.out.println(size + "size is");
        
        int y=0;
        //x=0;
       
        for(int i=0;i<size;i++){
            y+=80;
            new Thread(new Runnable(){
                
                int x=0;
                public void run(){
                    
                    for(int j=0;j<3;j++){
                        x+=80;
                        
                         getval(i,j);   
                      jp1.add(jlb[i][j] = new JLabel());
                        
                    }
                }
            }).start();
        }
        
        
        
        //int sz=lv.mat.length;
 /* Stopwatch stp = new Stopwatch();
        Stopwatch.sec obj = new Stopwatch.sec();
        obj.start();
        Stopwatch.min obj1 = new Stopwatch.min();
        obj1.start();
        Stopwatch.hr obj2 = new Stopwatch.hr();
        obj2.start();
        Thread arr[]=new Thread[100];
         */
/*
 Thread t = new Thread(new Runnable() {
            public void run() {
                while (true) {
                    int x = 0, y = 0;
                    for (int i = 0; i < size; i++) {
                        y += 80;
                        Stopwatch stp = new Stopwatch();
                        Stopwatch.sec obj = new Stopwatch.sec();
                        obj.start();
                        Stopwatch.min obj1 = new Stopwatch.min();
                        obj1.start();
                        Stopwatch.hr obj2 = new Stopwatch.hr();
                        obj2.start();

                        for (int j = 0; j < 3; j++) {
                            x += 80;
                            jp1.add(jlb[i][j] = new JLabel());
                            if (j == 0) {
                                jlb[i][j].setText(stp.i1 + "");
                            } else if (j == 1) {
                                jlb[i][j].setText(stp.i2 + "");
                            } else {
                                jlb[i][j].setText(stp.i3 + "");
                            }
                            jlb[i][j].setSize(50, 50);
                            jlb[i][j].setLocation(x, y);
                        }
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }

            }

        });

 */
    }//GEN-LAST:event_livecActionPerformed

    private void hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostActionPerformed
        String n = name.getText();
        java.sql.Date sd = new java.sql.Date(date.getDate().getTime());
        String st = stime.getText();
        Request r = null;
        String tp = (String) type.getSelectedItem();
        try {
            r = new Request();
            //r.cont();
            //System.out.println("it is "+flag);
            //r.ping();

            if (r.flag == 1) {
                String query = "Insert Into contest VALUES ('" + n + "','" + sd + "','" + tp + "','" + st + "') ";
                r.dout.flush();
                r.dout.writeUTF(query + "");
                
            } else {
                JOptionPane.showMessageDialog(null, "Server down");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Server down");
        }

    }//GEN-LAST:event_hostActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void compileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compileActionPerformed
        // TODO add your handling code here:
        Clang obj = new Clang();
        String code = editor.getText();
        int ty = lchoose.getSelectedIndex();
        obj.compile(code, ty);

    }//GEN-LAST:event_compileActionPerformed

    private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
        // TODO add your handling code here:
        Clang clang = new Clang();
        clang.run();
        clang.check();
    }//GEN-LAST:event_runActionPerformed

    private void qchooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qchooseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qchooseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Clienthost;
    private javax.swing.JFrame Signup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JButton compile;
    private javax.swing.JButton create_acc;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextPane editor;
    private javax.swing.JTextField ftime;
    private javax.swing.JFrame home;
    private javax.swing.JButton host;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel jp1;
    private javax.swing.JComboBox<String> lchoose;
    private javax.swing.JButton livec;
    private javax.swing.JButton login;
    private javax.swing.JButton logout;
    private javax.swing.JFrame lvc;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField passwd;
    private javax.swing.JPanel pn;
    private javax.swing.JFrame problempage;
    private javax.swing.JComboBox<String> qchoose;
    private javax.swing.JTextArea question;
    private javax.swing.JButton run;
    private javax.swing.JButton signup;
    private javax.swing.JTextField signup_email;
    private javax.swing.JTextField signup_name;
    private javax.swing.JPasswordField signup_passwd;
    private javax.swing.JPasswordField signup_passwd2;
    private javax.swing.JRadioButton signup_show;
    private javax.swing.JTextField stime;
    private javax.swing.JFrame tut;
    private javax.swing.JButton tutorials;
    private javax.swing.JTextPane txt1;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
